services:
  app:
    build: .
    depends_on:
      - db-tasks

  db-tasks:
    container_name: postgres_tms
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: new_db2
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  migrations:
    build: .
    depends_on:
      - db-tasks
    command: ./migrator -migrate


volumes:
  db_data: