env: "local"

server:

  grpc:
    host: "localhost"
    port: 50052
    timeout: 5s

  http:
    host: "localhost"
    port: 8080

database:
  dsn: "host=localhost user=admin password=admin dbname=new_db2 port=5432 sslmode=disable TimeZone=Europe/Moscow"


redis:
  host: "localhost"
  port: 6379
  password: ""  # If no password is set, leave this empty
  db: 0         # Select the Redis database (default is 0)