# redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-tasks
  template:
    metadata:
      labels:
        app: redis-tasks
    spec:
      containers:
        - name: redis-tasks
          image: redis:7.0-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-tasks
spec:
  selector:
    app: redis-tasks
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP